package com.applichic.chicsecret.utils

import com.applichic.chicsecret.R

val colors = arrayListOf(
    R.color.blue,
    R.color.red,
    R.color.green,
    R.color.purple,
    R.color.orange,
    R.color.indigo,
    R.color.teal,
    R.color.yellow,
    R.color.pink,
    R.color.black,
)

val icons = arrayListOf(
    "house_fill",
    "envelope_fill",
    "gamecontroller_fill",
    "creditcard_fill",
    "cart_fill",
    "car_fill",
    "text_book_closed_fill",
    "tv_fill",
    "music_note",
    "film_fill",
    "message_fill",
    "camera_fill",
    "paintbrush_pointed_fill",
    "headphones",
    "bolt_fill",
    "bandage_fill",
    "photo_fill",
    "doc_text_fill",
    "calendar",
    "tag_fill",
    "desktopcomputer",
    "leaf_fill",
    "person_2_circle_fill",
)

val uppercase = arrayListOf(
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z"
)

val numbers = arrayListOf("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")

val specialCharacters = arrayListOf(
    "!", "@", "#", "%", "&", "*", ","
)

val words = arrayListOf(
    "ability",
    "able",
    "about",
    "above",
    "accept",
    "according",
    "account",
    "across",
    "act",
    "action",
    "activity",
    "actually",
    "add",
    "address",
    "administration",
    "admit",
    "adult",
    "affect",
    "after",
    "again",
    "against",
    "age",
    "agency",
    "agent",
    "ago",
    "agree",
    "agreement",
    "ahead",
    "air",
    "all",
    "allow",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "although",
    "always",
    "american",
    "among",
    "amount",
    "analysis",
    "and",
    "animal",
    "another",
    "answer"
)